/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple_ice_cream;

import java.awt.TrayIcon;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.util.Collection;
import javax.persistence.Entity;
import javax.swing.JOptionPane;

/*
 * @author FaHad
 * Programed By Fahad ALfaify
 * www.fahad.alfaify.net
 */
public class IceCreamSelling extends javax.swing.JFrame {

    /**
     * Creates new form IceCreamSelling
     */
    public clsOrderItem [] order;
    public clsOrder Order= new clsOrder();
    private int _ordercount;
    public int _currentorder;
    private double _currenttotal;
    public double OrderTotal = 0;

    public IceCreamSelling(int ordercount) {
        
        this._ordercount = ordercount;
        this._currentorder = 0;
        if (this.order == null)
        {
            this.order = new clsOrderItem[ordercount];
        }
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        //co.setText(z);
        this.lblTotal.setText(String.valueOf(ordercount));
        this.setTitle("Prepare order");
        this.setLocationRelativeTo(null);
        this.lblCurrent.setText(String.valueOf(this._currentorder + 1));
        if (_ordercount == 1) {
            btnNext.setVisible(false);
            btnBack.setVisible(false);
            btnFinish.setEnabled(true);
        }
        this.fillForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioCAPPUCCINO = new javax.swing.JRadioButton();
        radioLATTE = new javax.swing.JRadioButton();
        radioESPRESSO = new javax.swing.JRadioButton();
        radioCOFEMOCHA = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        chAlmonds = new javax.swing.JCheckBox();
        chPeanut = new javax.swing.JCheckBox();
        chMint = new javax.swing.JCheckBox();
        chPeach = new javax.swing.JCheckBox();
        chLemon = new javax.swing.JCheckBox();
        chPumpkine = new javax.swing.JCheckBox();
        chNutella = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        txtSubTotal = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        buRest = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cNoTax = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simple_ice_cream/happycup400.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        radioCAPPUCCINO.setBackground(new java.awt.Color(153, 153, 153));
        radioCAPPUCCINO.setForeground(new java.awt.Color(255, 255, 255));
        radioCAPPUCCINO.setText("CAPPUCCINO 8 S.R");
        radioCAPPUCCINO.setActionCommand("8");
        radioCAPPUCCINO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCAPPUCCINOActionPerformed(evt);
            }
        });

        radioLATTE.setBackground(new java.awt.Color(153, 153, 153));
        radioLATTE.setForeground(new java.awt.Color(255, 255, 255));
        radioLATTE.setText("LATTE 9 S.R");
        radioLATTE.setActionCommand("9");
        radioLATTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLATTEActionPerformed(evt);
            }
        });

        radioESPRESSO.setBackground(new java.awt.Color(153, 153, 153));
        radioESPRESSO.setForeground(new java.awt.Color(255, 255, 255));
        radioESPRESSO.setText("ESPRESSO 8 S.R");
        radioESPRESSO.setActionCommand("8");
        radioESPRESSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioESPRESSOActionPerformed(evt);
            }
        });

        radioCOFEMOCHA.setBackground(new java.awt.Color(153, 153, 153));
        radioCOFEMOCHA.setForeground(new java.awt.Color(255, 255, 255));
        radioCOFEMOCHA.setText("COFE MOCHA10 S.R");
        radioCOFEMOCHA.setActionCommand("10");
        radioCOFEMOCHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCOFEMOCHAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCAPPUCCINO)
                    .addComponent(radioESPRESSO)
                    .addComponent(radioLATTE)
                    .addComponent(radioCOFEMOCHA))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioCAPPUCCINO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioLATTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioESPRESSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCOFEMOCHA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        chAlmonds.setBackground(new java.awt.Color(153, 153, 153));
        chAlmonds.setForeground(new java.awt.Color(255, 255, 255));
        chAlmonds.setText("CUP CAKE 2 S.R");
        chAlmonds.setActionCommand("2");
        chAlmonds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPeanut.setBackground(new java.awt.Color(153, 153, 153));
        chPeanut.setForeground(new java.awt.Color(255, 255, 255));
        chPeanut.setText("DONUT 1.5 S.R");
        chPeanut.setActionCommand("1.5");
        chPeanut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chMint.setBackground(new java.awt.Color(153, 153, 153));
        chMint.setForeground(new java.awt.Color(255, 255, 255));
        chMint.setText("LOTUS 0.5 S.R");
        chMint.setActionCommand("0.5");
        chMint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPeach.setBackground(new java.awt.Color(153, 153, 153));
        chPeach.setForeground(new java.awt.Color(255, 255, 255));
        chPeach.setText("COOKIE 3 S.R");
        chPeach.setActionCommand("3");
        chPeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chLemon.setBackground(new java.awt.Color(153, 153, 153));
        chLemon.setForeground(new java.awt.Color(255, 255, 255));
        chLemon.setText("MAVEN 2 S.R");
        chLemon.setActionCommand("2");
        chLemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chPumpkine.setBackground(new java.awt.Color(153, 153, 153));
        chPumpkine.setForeground(new java.awt.Color(255, 255, 255));
        chPumpkine.setText("SOUFFLE 2.5 S.R");
        chPumpkine.setActionCommand("2.5");
        chPumpkine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        chNutella.setBackground(new java.awt.Color(153, 153, 153));
        chNutella.setForeground(new java.awt.Color(255, 255, 255));
        chNutella.setText("BRAWNIE 4  S.R");
        chNutella.setActionCommand("4");
        chNutella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAlmondsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chAlmonds)
                    .addComponent(chPeanut)
                    .addComponent(chMint)
                    .addComponent(chPeach)
                    .addComponent(chLemon)
                    .addComponent(chPumpkine)
                    .addComponent(chNutella))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chAlmonds)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPeanut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chMint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPeach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chLemon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPumpkine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chNutella)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });

        txtTax.setEditable(false);
        txtTax.setBackground(new java.awt.Color(255, 255, 255));
        txtTax.setForeground(new java.awt.Color(255, 0, 0));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Total Without Tax");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tax");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item Total With Tax");

        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("S.R");

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        buRest.setText("Rest ");
        buRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buRestActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.setEnabled(false);
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setEnabled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCancelFocusLost(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buRest, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buRest)
                    .addComponent(btnFinish)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(btnCancel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cNoTax.setBackground(new java.awt.Color(153, 153, 153));
        cNoTax.setForeground(new java.awt.Color(255, 255, 51));
        cNoTax.setText("No TAX");
        cNoTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNoTaxActionPerformed(evt);
            }
        });

        jLabel14.setText("This Item");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cNoTax)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cNoTax))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Main");

        jLabel8.setText("Extra");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Item");

        lblCurrent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCurrent.setForeground(new java.awt.Color(102, 102, 102));
        lblCurrent.setText("1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Of");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setText("5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblCurrent)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTotal))
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(154, 154, 154))
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblCurrent)
                    .addComponent(jLabel12)
                    .addComponent(lblTotal))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        if (this.isvalidInput()) {

            this.fillItem();
            Order.setClsOrderItemCollection(order);
            if (!Order.Save()){
                JOptionPane.showMessageDialog(this, "An error while saving order");
                return;
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int i = 0; i < this._ordercount; i++) {
            this.OrderTotal += order[i].getTotalwithtax();
        }

        MainScreen ms = new MainScreen(this._ordercount, this.OrderTotal, this);
        this.setVisible(false);
        ms.setVisible(true);
    }//GEN-LAST:event_btnFinishActionPerformed
    private void resetForm() {
        txtSubTotal.setText("");
        txtTax.setText("");
        txtTotal.setText("");
        cNoTax.setSelected(false);
        chAlmonds.setSelected(false);
        chPeanut.setSelected(false);
        chMint.setSelected(false);
        chPeach.setSelected(false);
        chLemon.setSelected(false);
        chPumpkine.setSelected(false);
        chNutella.setSelected(false);
        radioCAPPUCCINO.setSelected(false);
        radioLATTE.setSelected(false);
        radioESPRESSO.setSelected(false);
        radioCOFEMOCHA.setSelected(false);
    }
    private void buRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buRestActionPerformed
        this.resetForm();

    }//GEN-LAST:event_buRestActionPerformed

    private boolean isvalidInput() {
        return (radioLATTE.isSelected() || radioESPRESSO.isSelected() || radioCOFEMOCHA.isSelected() || radioCAPPUCCINO.isSelected());
    }
 //ENUM('CAPPUCCINO', 'LATTE', 'ESPRESSO', 'COFE MOCHA')
    private void fillItem() {
        double TAXRATE = .06;
        if (this.order[this._currentorder] == null){
            this.order[this._currentorder] = new clsOrderItem();
        }
        this.order[this._currentorder].setItemId(this._currentorder+1);
        if (this.radioCAPPUCCINO.isSelected()) {
            this.order[this._currentorder].setType("CAPPUCCINO");
            
        } else if (this.radioLATTE.isSelected()) {
            this.order[this._currentorder].setType("LATTE");
            
        } else if (this.radioESPRESSO.isSelected()) {
            this.order[this._currentorder].setType("ESPRESSO");
            
        } else if (this.radioCOFEMOCHA.isSelected()) {
            this.order[this._currentorder].setType("COFE MOCHA");
            
        }
        this.order[this._currentorder].setAlmonds(chAlmonds.isSelected());
        this.order[this._currentorder].setLemon(chLemon.isSelected());
        this.order[this._currentorder].setMint(chMint.isSelected());
        this.order[this._currentorder].setNutella(chNutella.isSelected());
        this.order[this._currentorder].setPeach(chPeach.isSelected());
        this.order[this._currentorder].setPeanut(chPeanut.isSelected());
        this.order[this._currentorder].setPumpkin(chPumpkine.isSelected());
        if (this.cNoTax.isSelected()) {
            this.order[this._currentorder].setTax(0);
            this.order[this._currentorder].setTotalwithouttax(this._currenttotal);
            this.order[this._currentorder].setTotalwithtax(this._currenttotal);
        } else {
            this.order[this._currentorder].setTax(this._currenttotal * TAXRATE);
            this.order[this._currentorder].setTotalwithouttax(this._currenttotal);
            this.order[this._currentorder].setTotalwithtax(this._currenttotal + (this._currenttotal * TAXRATE));
        }

    }

    private void fillForm() {
        //ENUM('CAPPUCCINO', 'LATTE', 'ESPRESSO', 'COFE MOCHA')
        if (this.order[this._currentorder] != null) {
            if (this.order[this._currentorder].getType() == "CAPPUCCINO") {
                this.radioCAPPUCCINO.setSelected(true);
            } else if (this.order[this._currentorder].getType() == "LATTE") {
                this.radioLATTE.setSelected(true);
            } else if (this.order[this._currentorder].getType() == "ESPRESSO") {
                this.radioESPRESSO.setSelected(true);
            } else if (this.order[this._currentorder].getType() == "COFE MOCHA") {
                this.radioCOFEMOCHA.setSelected(true);
            }
            chAlmonds.setSelected(this.order[this._currentorder].getAlmonds());
            chLemon.setSelected(this.order[this._currentorder].getLemon());
            chMint.setSelected(this.order[this._currentorder].getMint());
            chNutella.setSelected(this.order[this._currentorder].getNutella());
            chPeach.setSelected(this.order[this._currentorder].getPeach());
            chPeanut.setSelected(this.order[this._currentorder].getPeanut());
            chPumpkine.setSelected(this.order[this._currentorder].getPumpkin());

            if (this.order[this._currentorder].getTax() > 0) {
                this.cNoTax.setSelected(true);

            } else {
                this.cNoTax.setSelected(false);

            }
            txtSubTotal.setText(String.valueOf(this.order[this._currentorder].getTotalwithouttax()));
            txtTax.setText(String.valueOf(this.order[this._currentorder].getTax()));
            txtTotal.setText(String.valueOf(this.order[this._currentorder].getTotalwithtax()));
        }
        this.lblCurrent.setText(String.valueOf(this._currentorder + 1));
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (this._currentorder + 2 == this._ordercount) {
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(true);
                this.btnNext.setEnabled(false);
                btnBack.setEnabled(true);

                this.fillItem();
                this.resetForm();

                this._currentorder++;
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {

            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);

                this.fillItem();
                this.resetForm();
                this._currentorder++;
                if (this._currentorder == 0) {
                    btnBack.setEnabled(false);
                } else {
                    btnBack.setEnabled(true);
                }
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }


    }//GEN-LAST:event_btnNextActionPerformed
    private void recalculate() {
        double total;
        double subtotal = 0;
        double TAXRATE = .06;
        double tax;

        if (cNoTax.isSelected()) {
            TAXRATE = 0;
        }
        if (radioCAPPUCCINO.isSelected()) {
            subtotal = subtotal + 8;
        } else if (radioLATTE.isSelected()) {
            subtotal = subtotal + 9;
        } else if (radioESPRESSO.isSelected()) {
            subtotal = subtotal + 8;
        } else if (radioCOFEMOCHA.isSelected()) {
            subtotal = subtotal + 10;
        }

        if (chAlmonds.isSelected()) {
            subtotal = subtotal + 2;
        }
        if (chPeanut.isSelected()) {
            subtotal = subtotal + 1.5;
        }
        if (chMint.isSelected()) {
            subtotal = subtotal + 0.5;
        }
        if (chPeach.isSelected()) {
            subtotal = subtotal + 3;
        }
        if (chLemon.isSelected()) {
            subtotal = subtotal + 2;
        }
        if (chPumpkine.isSelected()) {
            subtotal = subtotal + 2.5;
        }
        if (chNutella.isSelected()) {
            subtotal = subtotal + 4;
        }

        txtSubTotal.setText(Double.toString(subtotal));

        subtotal = Double.parseDouble(txtSubTotal.getText());
        this._currenttotal = subtotal;
        tax = (subtotal * TAXRATE);
        DecimalFormat df = new DecimalFormat("#.##");
        tax = Double.valueOf(df.format(tax));
        total = tax + subtotal;

        txtTax.setText(Double.toString(tax));
        txtTotal.setText(Double.toString(total));
    }
    private void radioCOFEMOCHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCOFEMOCHAActionPerformed
        if (radioCOFEMOCHA.isSelected()) {
            radioCAPPUCCINO.setSelected(false);
            radioLATTE.setSelected(false);
            radioESPRESSO.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioCOFEMOCHAActionPerformed

    private void radioESPRESSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioESPRESSOActionPerformed
        if (radioESPRESSO.isSelected()) {
            radioCAPPUCCINO.setSelected(false);
            radioLATTE.setSelected(false);
            radioCOFEMOCHA.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioESPRESSOActionPerformed

    private void radioLATTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLATTEActionPerformed
        if (radioLATTE.isSelected()) {
            radioCAPPUCCINO.setSelected(false);
            radioESPRESSO.setSelected(false);
            radioCOFEMOCHA.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioLATTEActionPerformed

    private void radioCAPPUCCINOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCAPPUCCINOActionPerformed
        if (radioCAPPUCCINO.isSelected()) {
            radioLATTE.setSelected(false);
            radioESPRESSO.setSelected(false);
            radioCOFEMOCHA.setSelected(false);
            recalculate();
        }
    }//GEN-LAST:event_radioCAPPUCCINOActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if (this._currentorder - 1 == 0) {
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);
                this.btnNext.setEnabled(true);
                btnBack.setEnabled(false);

                this.fillItem();
                this.resetForm();
                this._currentorder--;
                this.fillForm();
            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else {
            if (this._currentorder == 0) {
                return;
            }
            if (this.isvalidInput()) {
                this.btnFinish.setEnabled(false);
                btnBack.setEnabled(true);
                this.fillItem();
                this.resetForm();
                this._currentorder--;
                this.fillForm();

            } else {
                JOptionPane.showMessageDialog(this, "Please select Coffee type", "No type selected", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void chAlmondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAlmondsActionPerformed
        // TODO add your handling code here:
        recalculate();
    }//GEN-LAST:event_chAlmondsActionPerformed

    private void cNoTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNoTaxActionPerformed
        // TODO add your handling code here:
        recalculate();
    }//GEN-LAST:event_cNoTaxActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        MainScreen ms = new MainScreen();
        ms.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCancelFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton buRest;
    private javax.swing.JCheckBox cNoTax;
    private javax.swing.JCheckBox chAlmonds;
    private javax.swing.JCheckBox chLemon;
    private javax.swing.JCheckBox chMint;
    private javax.swing.JCheckBox chNutella;
    private javax.swing.JCheckBox chPeach;
    private javax.swing.JCheckBox chPeanut;
    private javax.swing.JCheckBox chPumpkine;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton radioCAPPUCCINO;
    private javax.swing.JRadioButton radioCOFEMOCHA;
    private javax.swing.JRadioButton radioESPRESSO;
    private javax.swing.JRadioButton radioLATTE;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
